// ─── Monthly Revenue ──────────────────────────────────────────────────────────
export const MONTHLY_REVENUE = [
  { month: "Jan", revenue: 420000, orders: 52, customers: 38 },
  { month: "Feb", revenue: 385000, orders: 48, customers: 35 },
  { month: "Mar", revenue: 510000, orders: 63, customers: 47 },
  { month: "Apr", revenue: 478000, orders: 58, customers: 42 },
  { month: "May", revenue: 620000, orders: 74, customers: 56 },
  { month: "Jun", revenue: 590000, orders: 71, customers: 53 },
  { month: "Jul", revenue: 680000, orders: 82, customers: 61 },
  { month: "Aug", revenue: 724000, orders: 89, customers: 67 },
  { month: "Sep", revenue: 698000, orders: 85, customers: 64 },
  { month: "Oct", revenue: 810000, orders: 98, customers: 74 },
  { month: "Nov", revenue: 945000, orders: 115, customers: 86 },
  { month: "Dec", revenue: 1120000, orders: 138, customers: 102 },
];

export const WEEKLY_REVENUE = [
  { day: "Mon", revenue: 38400, orders: 12 },
  { day: "Tue", revenue: 52100, orders: 18 },
  { day: "Wed", revenue: 47300, orders: 15 },
  { day: "Thu", revenue: 61800, orders: 21 },
  { day: "Fri", revenue: 84200, orders: 28 },
  { day: "Sat", revenue: 96500, orders: 32 },
  { day: "Sun", revenue: 71000, orders: 24 },
];

// ─── Order Status ─────────────────────────────────────────────────────────────
export const ORDER_STATUS_DATA = [
  { name: "Delivered", value: 342, color: "#2BB9B4" },
  { name: "Processing", value: 87, color: "#E8522A" },
  { name: "Dispatched", value: 54, color: "#6366f1" },
  { name: "Pending", value: 38, color: "#f59e0b" },
  { name: "Cancelled", value: 22, color: "#ef4444" },
];

// ─── Category Sales ───────────────────────────────────────────────────────────
export const CATEGORY_SALES = [
  { category: "Skin Care", sales: 285000, units: 342 },
  { category: "Face Care", sales: 198000, units: 238 },
  { category: "Body Care", sales: 145000, units: 174 },
  { category: "Head Care", sales: 112000, units: 134 },
  { category: "Sun Care", sales: 98000, units: 118 },
  { category: "Lip Care", sales: 67000, units: 80 },
  { category: "Hand Care", sales: 54000, units: 65 },
  { category: "Acne Care", sales: 43000, units: 52 },
];

// ─── Top Products ─────────────────────────────────────────────────────────────
export const TOP_PRODUCTS = [
  { name: "CeraVe Moisturizing Cream", sales: 148, revenue: 473600, stock: 23 },
  { name: "The Ordinary Niacinamide 10%", sales: 134, revenue: 241200, stock: 45 },
  { name: "Aveeno Daily Moisturizer", sales: 121, revenue: 424000, stock: 18 },
  { name: "L'Oréal Revitalift Serum", sales: 98, revenue: 490000, stock: 31 },
  { name: "Vitamin C Brightening SPF", sales: 87, revenue: 382800, stock: 12 },
  { name: "Madagascar Centella Cream", sales: 74, revenue: 251600, stock: 37 },
];

// ─── Orders ──────────────────────────────────────────────────────────────────
export const ORDERS = [
  {
    id: "ORD-1001",
    customer: "Amal Karunaratne",
    email: "amal.k@gmail.com",
    phone: "+94 77 234 5678",
    address: "45 Galle Rd, Colombo 03",
    city: "Colombo",
    date: "2026-03-25",
    status: "pending",
    payment: "CocoPay",
    items: [
      { name: "CeraVe Moisturizing Cream", qty: 2, price: 3200 },
      { name: "The Ordinary Niacinamide", qty: 1, price: 1800 },
    ],
    total: 8200,
    notes: "Please pack carefully.",
  },
  {
    id: "ORD-1002",
    customer: "Nimal Perera",
    email: "nimal.p@gmail.com",
    phone: "+94 76 345 6789",
    address: "12 Marine Dr, Galle",
    city: "Galle",
    date: "2026-03-24",
    status: "processing",
    payment: "CocoPay",
    items: [
      { name: "Aveeno Daily Moisturizer", qty: 1, price: 3500 },
      { name: "L'Oréal Revitalift Serum", qty: 1, price: 5000 },
    ],
    total: 8500,
    notes: "",
  },
  {
    id: "ORD-1003",
    customer: "Isuri Wijesinghe",
    email: "isuri.w@gmail.com",
    phone: "+94 71 456 7890",
    address: "78 Kandy Rd, Kurunegala",
    city: "Kurunegala",
    date: "2026-03-24",
    status: "dispatched",
    payment: "CocoPay",
    items: [
      { name: "Vitamin C Brightening SPF", qty: 2, price: 4400 },
    ],
    total: 8800,
    notes: "",
    trackingId: "TRK-88234",
    courier: "Kapruka",
  },
  {
    id: "ORD-1004",
    customer: "Sarah Fernando",
    email: "sarah.f@gmail.com",
    phone: "+94 70 567 8901",
    address: "23 Peradeniya Rd, Kandy",
    city: "Kandy",
    date: "2026-03-23",
    status: "delivered",
    payment: "CocoPay",
    items: [
      { name: "CeraVe Moisturizing Cream", qty: 1, price: 3200 },
      { name: "Madagascar Centella Cream", qty: 1, price: 3400 },
      { name: "Vitamin C Brightening SPF", qty: 1, price: 4400 },
    ],
    total: 11000,
    notes: "",
    trackingId: "TRK-87901",
    courier: "Kapruka",
  },
  {
    id: "ORD-1005",
    customer: "Jason Thambipillai",
    email: "jason.t@gmail.com",
    phone: "+94 75 678 9012",
    address: "56 Hospital Rd, Jaffna",
    city: "Jaffna",
    date: "2026-03-23",
    status: "delivered",
    payment: "CocoPay",
    items: [
      { name: "The Ordinary Niacinamide 10%", qty: 3, price: 1800 },
    ],
    total: 5400,
    notes: "Fragile items.",
    trackingId: "TRK-87845",
    courier: "DHL",
  },
  {
    id: "ORD-1006",
    customer: "Riya Patel",
    email: "riya.p@gmail.com",
    phone: "+94 72 789 0123",
    address: "34 Negombo Rd, Negombo",
    city: "Negombo",
    date: "2026-03-22",
    status: "cancelled",
    payment: "CocoPay",
    items: [
      { name: "L'Oréal Revitalift Serum", qty: 1, price: 5000 },
    ],
    total: 5000,
    notes: "Customer requested cancellation.",
  },
  {
    id: "ORD-1007",
    customer: "Emma Rodrigo",
    email: "emma.r@gmail.com",
    phone: "+94 77 890 1234",
    address: "11 Gampaha Rd, Gampaha",
    city: "Gampaha",
    date: "2026-03-22",
    status: "processing",
    payment: "CocoPay",
    items: [
      { name: "Aveeno Daily Moisturizer", qty: 2, price: 3500 },
      { name: "CeraVe Moisturizing Cream", qty: 1, price: 3200 },
    ],
    total: 10200,
    notes: "",
  },
  {
    id: "ORD-1008",
    customer: "Hasan Ahamed",
    email: "hasan.a@gmail.com",
    phone: "+94 76 901 2345",
    address: "67 Ampara Rd, Ampara",
    city: "Ampara",
    date: "2026-03-21",
    status: "delivered",
    payment: "CocoPay",
    items: [
      { name: "Vitamin C Brightening SPF", qty: 1, price: 4400 },
      { name: "The Ordinary Niacinamide 10%", qty: 2, price: 1800 },
    ],
    total: 8000,
    notes: "",
    trackingId: "TRK-87412",
    courier: "Kapruka",
  },
  {
    id: "ORD-1009",
    customer: "Leena Silva",
    email: "leena.s@gmail.com",
    phone: "+94 71 012 3456",
    address: "29 Kalutara Rd, Kalutara",
    city: "Kalutara",
    date: "2026-03-20",
    status: "dispatched",
    payment: "CocoPay",
    items: [
      { name: "Madagascar Centella Cream", qty: 2, price: 3400 },
    ],
    total: 6800,
    notes: "",
    trackingId: "TRK-87333",
    courier: "DHL",
  },
  {
    id: "ORD-1010",
    customer: "Daniel Kumarasinghe",
    email: "daniel.k@gmail.com",
    phone: "+94 70 123 4567",
    address: "88 Matara Rd, Matara",
    city: "Matara",
    date: "2026-03-20",
    status: "pending",
    payment: "CocoPay",
    items: [
      { name: "L'Oréal Revitalift Serum", qty: 2, price: 5000 },
      { name: "CeraVe Moisturizing Cream", qty: 2, price: 3200 },
    ],
    total: 16400,
    notes: "Gift wrap please.",
  },
  {
    id: "ORD-1011",
    customer: "Maya De Silva",
    email: "maya.d@gmail.com",
    phone: "+94 75 234 5678",
    address: "15 Kotte Rd, Sri Jayawardenepura",
    city: "Colombo",
    date: "2026-03-19",
    status: "delivered",
    payment: "CocoPay",
    items: [
      { name: "Aveeno Daily Moisturizer", qty: 1, price: 3500 },
    ],
    total: 3500,
    notes: "",
    trackingId: "TRK-87120",
    courier: "Kapruka",
  },
  {
    id: "ORD-1012",
    customer: "Noah Samarawickrama",
    email: "noah.s@gmail.com",
    phone: "+94 72 345 6789",
    address: "42 Ratnapura Rd, Ratnapura",
    city: "Ratnapura",
    date: "2026-03-19",
    status: "processing",
    payment: "CocoPay",
    items: [
      { name: "Vitamin C Brightening SPF", qty: 3, price: 4400 },
      { name: "Madagascar Centella Cream", qty: 1, price: 3400 },
    ],
    total: 16600,
    notes: "",
  },
];

// ─── Brands (matches dbo.Brands) ─────────────────────────────────────────────
export const BRANDS = [
  { Brandid: 1, name: "CeraVe",       barndimage: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=200", createdate: "2025-01-10", lastupdated: null },
  { Brandid: 2, name: "The Ordinary", barndimage: "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=200", createdate: "2025-01-12", lastupdated: null },
  { Brandid: 3, name: "Aveeno",       barndimage: "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=200", createdate: "2025-01-15", lastupdated: null },
  { Brandid: 4, name: "L'Oréal",      barndimage: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=200", createdate: "2025-02-01", lastupdated: null },
  { Brandid: 5, name: "Neutrogena",   barndimage: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=200", createdate: "2025-02-05", lastupdated: null },
  { Brandid: 6, name: "Cetaphil",     barndimage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=200", createdate: "2025-02-10", lastupdated: null },
  { Brandid: 7, name: "Madagascar",   barndimage: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=200", createdate: "2025-03-01", lastupdated: null },
  { Brandid: 8, name: "Tenzy",        barndimage: "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=200", createdate: "2025-03-10", lastupdated: null },
];

// ─── Categories (matches dbo.Category) ───────────────────────────────────────
export const CATEGORIES = [
  { catagoryID: 1, categorytype: "Skin" },
  { catagoryID: 2, categorytype: "Face" },
  { catagoryID: 3, categorytype: "Body" },
  { catagoryID: 4, categorytype: "Head" },
  { catagoryID: 5, categorytype: "Sun" },
  { catagoryID: 6, categorytype: "Lips" },
  { catagoryID: 7, categorytype: "Hand" },
  { catagoryID: 8, categorytype: "Acne" },
];

// ─── Concern Types (matches dbo.ConcernTypes) ─────────────────────────────────
export const CONCERN_TYPES = [
  { ConcernTypeId: 1, ConcernType: "Dry Skin",      description: "Products targeting dehydration and flakiness" },
  { ConcernTypeId: 2, ConcernType: "Oily Skin",     description: "Products that control excess sebum" },
  { ConcernTypeId: 3, ConcernType: "Sensitive",     description: "Gentle formulas for reactive skin" },
  { ConcernTypeId: 4, ConcernType: "Anti-Ageing",   description: "Targets fine lines and wrinkles" },
  { ConcernTypeId: 5, ConcernType: "Brightening",   description: "Improves skin tone and radiance" },
  { ConcernTypeId: 6, ConcernType: "Acne-Prone",    description: "Reduces breakouts and blemishes" },
  { ConcernTypeId: 7, ConcernType: "Hyperpigmentation", description: "Fades dark spots and uneven tone" },
  { ConcernTypeId: 8, ConcernType: "Sun Protection", description: "UV protection and after-sun care" },
];

// ─── Payment Types (matches dbo.PaymentType) ──────────────────────────────────
export const PAYMENT_TYPES = [
  { PaymentTypeId: 1, PaymentType: "Full Payment" },
  { PaymentTypeId: 2, PaymentType: "CocoPay 3 Months" },
  { PaymentTypeId: 3, PaymentType: "CocoPay 6 Months" },
  { PaymentTypeId: 4, PaymentType: "CocoPay 12 Months" },
];

// ─── Products — DB-schema aligned (matches all product tables) ────────────────
export const ADMIN_PRODUCTS = [
  {
    productid: 1,
    name: "CeraVe Moisturizing Cream",
    brandid: 1,
    categoryid: 1,
    description: "A rich, non-greasy moisturizing cream with three essential ceramides and hyaluronic acid. Developed with dermatologists for normal to dry skin.",
    weight: 340.000,
    insale: true,
    sold: 148,
    // ProductInventory
    stock: 23,
    // ProductPricing (active pricing row)
    price: 3200.00,
    discountrate: 10.00,
    StartUTC: "2026-01-01",
    EndUTC: null,
    // ProductImages
    images: [
      { ImageId: 1, ImageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
      { ImageId: 2, ImageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600", IsPrimary: false, SortOrder: 2 },
    ],
    // ProductConcerns
    concerns: [1, 3],
    // ProductPaymentOptions
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
      { PaymentTypeId: 2, instalment: 3 },
    ],
    // ProductFAQ
    faqs: [
      { FAQId: 1, Question: "Is this suitable for sensitive skin?", Answer: "Yes, CeraVe is developed with dermatologists and is gentle enough for sensitive skin." },
      { FAQId: 2, Question: "Can I use this as a night cream?", Answer: "Absolutely. Apply a generous layer before bed for overnight hydration." },
    ],
  },
  {
    productid: 2,
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brandid: 2,
    categoryid: 2,
    description: "High-strength vitamin and mineral blemish formula. Niacinamide (Vitamin B3) reduces the appearance of skin blemishes and congestion.",
    weight: 30.000,
    insale: false,
    sold: 134,
    stock: 45,
    price: 1800.00,
    discountrate: 0,
    StartUTC: "2026-01-01",
    EndUTC: null,
    images: [
      { ImageId: 3, ImageUrl: "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
    ],
    concerns: [2, 6, 7],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
    ],
    faqs: [
      { FAQId: 3, Question: "How often should I use this?", Answer: "Use morning and night after water-based serums and before oils or creams." },
    ],
  },
  {
    productid: 3,
    name: "Aveeno Daily Moisturizing Lotion",
    brandid: 3,
    categoryid: 3,
    description: "Formulated with Active Naturals Oat and rich emollients, this lotion absorbs quickly to moisturize and improve the look and feel of skin.",
    weight: 400.000,
    insale: true,
    sold: 121,
    stock: 18,
    price: 3500.00,
    discountrate: 10.00,
    StartUTC: "2026-02-01",
    EndUTC: null,
    images: [
      { ImageId: 4, ImageUrl: "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
      { ImageId: 5, ImageUrl: "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=600", IsPrimary: false, SortOrder: 2 },
    ],
    concerns: [1, 3],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
      { PaymentTypeId: 2, instalment: 3 },
    ],
    faqs: [],
  },
  {
    productid: 4,
    name: "L'Oréal Revitalift 1.5% Pure Hyaluronic Acid Serum",
    brandid: 4,
    categoryid: 2,
    description: "Concentrated anti-wrinkle + plumping serum with 1.5% pure hyaluronic acid. Visibly reduces wrinkles and plumps skin in 1 week.",
    weight: 30.000,
    insale: false,
    sold: 98,
    stock: 31,
    price: 5000.00,
    discountrate: 0,
    StartUTC: "2026-01-01",
    EndUTC: null,
    images: [
      { ImageId: 6, ImageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
    ],
    concerns: [1, 4],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
      { PaymentTypeId: 2, instalment: 3 },
      { PaymentTypeId: 3, instalment: 6 },
    ],
    faqs: [
      { FAQId: 4, Question: "Can I use this with retinol?", Answer: "Yes, hyaluronic acid pairs well with retinol. Apply the serum first, then retinol on top." },
    ],
  },
  {
    productid: 5,
    name: "Vitamin C Brightening SPF 30",
    brandid: 8,
    categoryid: 5,
    description: "Daily brightening sunscreen with SPF 30 and stabilised Vitamin C. Protects against UVA/UVB while visibly brightening skin tone.",
    weight: 50.000,
    insale: true,
    sold: 87,
    stock: 12,
    price: 4400.00,
    discountrate: 10.00,
    StartUTC: "2026-03-01",
    EndUTC: null,
    images: [
      { ImageId: 7, ImageUrl: "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
    ],
    concerns: [5, 7, 8],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
    ],
    faqs: [],
  },
  {
    productid: 6,
    name: "Madagascar Centella Deep Repair Cream",
    brandid: 7,
    categoryid: 1,
    description: "Deep repair cream enriched with Centella Asiatica extract. Soothes redness, repairs the skin barrier and provides long-lasting moisture.",
    weight: 60.000,
    insale: false,
    sold: 74,
    stock: 37,
    price: 3400.00,
    discountrate: 0,
    StartUTC: "2026-01-01",
    EndUTC: null,
    images: [
      { ImageId: 8, ImageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
    ],
    concerns: [3, 6],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
      { PaymentTypeId: 2, instalment: 3 },
    ],
    faqs: [],
  },
  {
    productid: 7,
    name: "Neutrogena Hydro Boost Water Gel",
    brandid: 5,
    categoryid: 1,
    description: "Oil-free, water-based gel that absorbs quickly to quench skin and lock in hydration. Non-comedogenic and dermatologist tested.",
    weight: 50.000,
    insale: true,
    sold: 62,
    stock: 0,
    price: 4800.00,
    discountrate: 10.00,
    StartUTC: "2026-02-15",
    EndUTC: null,
    images: [
      { ImageId: 9, ImageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=600", IsPrimary: true, SortOrder: 1 },
    ],
    concerns: [1, 2],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
    ],
    faqs: [],
  },
  {
    productid: 8,
    name: "Cetaphil Gentle Skin Cleanser",
    brandid: 6,
    categoryid: 2,
    description: "Mild, non-irritating formula that cleanses without stripping the skin of its natural protective oils. Suitable for all skin types.",
    weight: 250.000,
    insale: false,
    sold: 58,
    stock: 54,
    price: 2600.00,
    discountrate: 0,
    StartUTC: "2026-01-01",
    EndUTC: null,
    images: [
      { ImageId: 10, ImageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=600", IsPrimary: true,  SortOrder: 1 },
      { ImageId: 11, ImageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=600", IsPrimary: false, SortOrder: 2 },
    ],
    concerns: [1, 2, 3, 6],
    paymentOptions: [
      { PaymentTypeId: 1, instalment: null },
      { PaymentTypeId: 2, instalment: 3 },
    ],
    faqs: [
      { FAQId: 5, Question: "Is it suitable for babies?", Answer: "Yes, Cetaphil Gentle Cleanser is mild enough for babies and young children." },
    ],
  },
];

// ─── Customers ────────────────────────────────────────────────────────────────
export const CUSTOMERS = [
  {
    id: "CUS-001",
    name: "Amal Karunaratne",
    email: "amal.k@gmail.com",
    phone: "+94 77 234 5678",
    city: "Colombo",
    joined: "2025-08-12",
    orders: 6,
    totalSpent: 48200,
    lastOrder: "2026-03-25",
    status: "active",
  },
  {
    id: "CUS-002",
    name: "Nimal Perera",
    email: "nimal.p@gmail.com",
    phone: "+94 76 345 6789",
    city: "Galle",
    joined: "2025-09-03",
    orders: 4,
    totalSpent: 32100,
    lastOrder: "2026-03-24",
    status: "active",
  },
  {
    id: "CUS-003",
    name: "Isuri Wijesinghe",
    email: "isuri.w@gmail.com",
    phone: "+94 71 456 7890",
    city: "Kurunegala",
    joined: "2025-10-18",
    orders: 3,
    totalSpent: 21400,
    lastOrder: "2026-03-24",
    status: "active",
  },
  {
    id: "CUS-004",
    name: "Sarah Fernando",
    email: "sarah.f@gmail.com",
    phone: "+94 70 567 8901",
    city: "Kandy",
    joined: "2025-07-22",
    orders: 8,
    totalSpent: 67500,
    lastOrder: "2026-03-23",
    status: "active",
  },
  {
    id: "CUS-005",
    name: "Jason Thambipillai",
    email: "jason.t@gmail.com",
    phone: "+94 75 678 9012",
    city: "Jaffna",
    joined: "2025-11-05",
    orders: 2,
    totalSpent: 10800,
    lastOrder: "2026-03-23",
    status: "active",
  },
  {
    id: "CUS-006",
    name: "Riya Patel",
    email: "riya.p@gmail.com",
    phone: "+94 72 789 0123",
    city: "Negombo",
    joined: "2025-12-14",
    orders: 1,
    totalSpent: 0,
    lastOrder: "2026-03-22",
    status: "inactive",
  },
  {
    id: "CUS-007",
    name: "Emma Rodrigo",
    email: "emma.r@gmail.com",
    phone: "+94 77 890 1234",
    city: "Gampaha",
    joined: "2026-01-08",
    orders: 3,
    totalSpent: 24600,
    lastOrder: "2026-03-22",
    status: "active",
  },
  {
    id: "CUS-008",
    name: "Hasan Ahamed",
    email: "hasan.a@gmail.com",
    phone: "+94 76 901 2345",
    city: "Ampara",
    joined: "2025-06-30",
    orders: 5,
    totalSpent: 38200,
    lastOrder: "2026-03-21",
    status: "active",
  },
  {
    id: "CUS-009",
    name: "Leena Silva",
    email: "leena.s@gmail.com",
    phone: "+94 71 012 3456",
    city: "Kalutara",
    joined: "2026-02-14",
    orders: 2,
    totalSpent: 13600,
    lastOrder: "2026-03-20",
    status: "active",
  },
  {
    id: "CUS-010",
    name: "Daniel Kumarasinghe",
    email: "daniel.k@gmail.com",
    phone: "+94 70 123 4567",
    city: "Matara",
    joined: "2025-05-11",
    orders: 9,
    totalSpent: 82400,
    lastOrder: "2026-03-20",
    status: "active",
  },
];

// ─── Dispatch Queue ───────────────────────────────────────────────────────────
export const DISPATCH_QUEUE = ORDERS.filter((o) =>
  ["processing", "dispatched"].includes(o.status)
);

// ─── Summary Stats ────────────────────────────────────────────────────────────
export const STATS = {
  totalRevenue: 7580000,
  revenueChange: 18.4,
  totalOrders: 543,
  ordersChange: 12.1,
  totalCustomers: 287,
  customersChange: 9.3,
  totalProducts: 48,
  lowStock: 3,
  pendingOrders: 38,
  dispatchedToday: 12,
  avgOrderValue: 13960,
  returnRate: 2.1,
};

// ─── Product Reviews (matches dbo.ProductReview) ──────────────────────────────
export const REVIEWS = [
  { ID: 1,  productid: 1, userid: "u-001", customerName: "Amal Karunaratne", rate: 5, comment: "Amazing moisturizer! My skin feels so hydrated and the texture is perfect. Will definitely repurchase.", createdUTC: "2026-03-20" },
  { ID: 2,  productid: 1, userid: "u-004", customerName: "Sarah Fernando",   rate: 4, comment: "Great product, absorbs quickly and doesn't feel greasy. Slight scent but fades quickly.", createdUTC: "2026-03-18" },
  { ID: 3,  productid: 1, userid: "u-007", customerName: "Emma Rodrigo",     rate: 5, comment: "Best moisturizer I've ever used. Dermatologist recommended and it really works.", createdUTC: "2026-03-15" },
  { ID: 4,  productid: 2, userid: "u-002", customerName: "Nimal Perera",     rate: 5, comment: "Cleared my pores in just 2 weeks. Skin looks smoother and brighter. Highly recommend!", createdUTC: "2026-03-22" },
  { ID: 5,  productid: 2, userid: "u-008", customerName: "Hasan Ahamed",     rate: 4, comment: "Good product but takes time to see results. Packaging could be improved.", createdUTC: "2026-03-19" },
  { ID: 6,  productid: 3, userid: "u-003", customerName: "Isuri Wijesinghe", rate: 5, comment: "Love this lotion! Very lightweight and keeps my skin moisturised all day long.", createdUTC: "2026-03-21" },
  { ID: 7,  productid: 3, userid: "u-009", customerName: "Leena Silva",      rate: 3, comment: "Decent moisturizer but the pump dispenser stopped working after a week. Product itself is fine.", createdUTC: "2026-03-17" },
  { ID: 8,  productid: 4, userid: "u-004", customerName: "Sarah Fernando",   rate: 5, comment: "This serum is incredible. My skin looks plump and the fine lines around my eyes have visibly reduced.", createdUTC: "2026-03-23" },
  { ID: 9,  productid: 4, userid: "u-010", customerName: "Daniel Kumarasinghe", rate: 4, comment: "Good serum but expensive for the amount. Results are noticeable after consistent use.", createdUTC: "2026-03-16" },
  { ID: 10, productid: 5, userid: "u-005", customerName: "Jason Thambipillai", rate: 5, comment: "Great SPF! No white cast and feels lightweight. The Vitamin C gives a nice glow too.", createdUTC: "2026-03-24" },
  { ID: 11, productid: 6, userid: "u-003", customerName: "Isuri Wijesinghe", rate: 4, comment: "Very soothing for my sensitive skin. Redness reduced significantly.", createdUTC: "2026-03-20" },
  { ID: 12, productid: 8, userid: "u-002", customerName: "Nimal Perera",     rate: 2, comment: "Too watery for my dry skin. Didn't feel hydrated enough. Not for dry skin types.", createdUTC: "2026-03-14" },
  { ID: 13, productid: 8, userid: "u-001", customerName: "Amal Karunaratne", rate: 5, comment: "Perfect cleanser! Gentle, non-stripping and works great as a morning wash.", createdUTC: "2026-03-12" },
  { ID: 14, productid: 7, userid: "u-004", customerName: "Sarah Fernando",   rate: 3, comment: "Good hydration but slightly sticky in our Sri Lanka humidity. Works better in AC rooms.", createdUTC: "2026-03-10" },
];
