import { sellingpro } from "./const";

export const SellingProducts = [
  {
    id: 1,
    name: "Aveeno body lotion",
    price: 20000,
    discountPercent: 20,
    inSale: true,
    stockCount: 12,
    outOfStock: false,
    image: sellingpro.aveeno,
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 3,
    category: "Skin",
    sku: "BS-0001",
    description:
      "Daily moisturizing body lotion for soft, smooth skin. Lightweight feel with long-lasting hydration.",
    size: "354ml",
    weight: "354g",
    images: [sellingpro.aveeno],
    concernIds: [4],
  },
  {
    id: 2,
    name: "Hydra Cream 24H",
    price: 18500,
    discountPercent: 15,
    inSale: true,
    stockCount: 0,
    outOfStock: true,
    image:
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: "Hydra",
    category: "Face",
    sku: "BS-0002",
    description:
      "24-hour hydration cream designed to support a healthy moisture barrier with a smooth, non-greasy finish.",
    size: "50ml",
    weight: "50g",
    images: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [4, 6],
  },
  {
    id: 3,
    name: "Rose Cleanse Foam",
    price: 12500,
    discountPercent: 10,
    inSale: true,
    stockCount: 7,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 2,
    category: "Face",
    sku: "BS-0003",
    description:
      "Gentle foaming cleanser with a fresh feel. Helps remove daily impurities while keeping skin comfortable.",
    size: "150ml",
    weight: "150g",
    images: [
      "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [1, 4],
  },
  {
    id: 4,
    name: "Vitamin C Bright Kit",
    price: 24000,
    discountPercent: 25,
    inSale: true,
    stockCount: 3,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 4,

    brandId: 4,
    category: "Face",
    sku: "BS-0004",
    description:
      "Brightening kit powered by Vitamin C to support glow and a more even-looking complexion over time.",
    size: "Kit",
    weight: "N/A",
    images: [
      "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [3, 4],
  },
  {
    id: 5,
    name: "Night Repair Oil",
    price: 31500,
    discountPercent: 18,
    inSale: true,
    stockCount: 9,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1611930022073-5f4f6c21f2e2?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 1,
    category: "Face",
    sku: "BS-0005",
    description:
      "Overnight facial oil blend to support a nourished look by morning. Smooth texture with a soft finish.",
    size: "30ml",
    weight: "30g",
    images: [
      "https://images.unsplash.com/photo-1611930022073-5f4f6c21f2e2?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [5, 1, 4],
  },
  {
    id: 6,
    name: "Soothing Toner",
    price: 9900,
    discountPercent: 12,
    inSale: true,
    stockCount: 18,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 2,
    category: "Face",
    sku: "BS-0006",
    description:
      "Refreshing toner made for a comfortable feel. Preps skin for the next steps in your routine.",
    size: "200ml",
    weight: "200g",
    images: [
      "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [4, 6, 2],
  },
  {
    id: 7,
    name: "SPF 50+ Shield",
    price: 21000,
    discountPercent: 22,
    inSale: true,
    stockCount: 0,
    outOfStock: true,
    image:
      "https://images.unsplash.com/photo-1620916566653-8fd8f4c86b2b?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 5,
    category: "Face",
    sku: "BS-0007",
    description:
      "High-protection SPF 50+ formula designed for daily wear. Lightweight feel with a comfortable finish.",
    size: "50ml",
    weight: "50g",
    images: [
      "https://images.unsplash.com/photo-1620916566653-8fd8f4c86b2b?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [4],
  },
  {
    id: 8,
    name: "AHA Exfoliating Pad",
    price: 16500,
    discountPercent: 14,
    inSale: true,
    stockCount: 5,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1612810436541-15f7a2f29f8c?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 5,
    category: "Face",
    sku: "BS-0008",
    description:
      "Exfoliating pads with AHA to help refine the look of texture. Convenient and easy to use.",
    size: "60 pads",
    weight: "N/A",
    images: [
      "https://images.unsplash.com/photo-1612810436541-15f7a2f29f8c?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [1],
  },
  {
    id: 9,
    name: "Lip Butter Balm",
    price: 6500,
    discountPercent: 8,
    inSale: true,
    stockCount: 22,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 5,
    category: "Face",
    sku: "BS-0009",
    description:
      "Rich lip balm with a buttery feel for daily comfort. Smooth application with a soft sheen.",
    size: "10g",
    weight: "10g",
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [2, 3, 5],
  },
  {
    id: 10,
    name: "Clay Detox Mask",
    price: 14000,
    discountPercent: 16,
    inSale: true,
    stockCount: 2,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 1,
    category: "Face",
    sku: "BS-0010",
    description:
      "Clay mask designed to leave skin feeling fresh and clean. Ideal as a weekly reset step.",
    size: "100ml",
    weight: "100g",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [2, 3, 4],
  },
  {
    id: 11,
    name: "Tea Tree Spot Gel",
    price: 8900,
    discountPercent: 12,
    inSale: true,
    stockCount: 14,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1612810436541-15f7a2f29f8c?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 2,
    category: "Face",
    sku: "BS-0011",
    description:
      "Targeted spot gel with tea tree to help calm the look of blemishes. Lightweight and easy to apply.",
    size: "15ml",
    weight: "15g",
    images: [
      "https://images.unsplash.com/photo-1612810436541-15f7a2f29f8c?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [4],
  },
  {
    id: 12,
    name: "Hyaluronic Serum",
    price: 19500,
    discountPercent: 18,
    inSale: true,
    stockCount: 6,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 3,
    category: "Face",
    sku: "BS-0012",
    description:
      "Plumping hyaluronic serum for a hydrated, bouncy look. Layers well under moisturizer and makeup.",
    size: "30ml",
    weight: "30g",
    images: [
      "https://images.unsplash.com/photo-1585232351009-aa87416fca90?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [6],
  },
  {
    id: 13,
    name: "Gentle Micellar Water",
    price: 11500,
    discountPercent: 10,
    inSale: true,
    stockCount: 20,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 5,
    category: "Face",
    sku: "BS-0013",
    description:
      "Micellar cleansing water to remove makeup and impurities with a fresh, comfortable feel. No harsh residue.",
    size: "250ml",
    weight: "250g",
    images: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [1, 6],
  },
  {
    id: 14,
    name: "Nourishing Hair Mask",
    price: 22500,
    discountPercent: 20,
    inSale: true,
    stockCount: 4,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 4,

    brandId: 2,
    category: "Head",
    sku: "BS-0014",
    description:
      "Deep conditioning hair mask for smoother-looking hair. Ideal for weekly care and shine support.",
    size: "200ml",
    weight: "200g",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [4],
  },
  {
    id: 15,
    name: "Scalp Refresh Shampoo",
    price: 16800,
    discountPercent: 15,
    inSale: true,
    stockCount: 10,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1620916566653-8fd8f4c86b2b?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 6,
    category: "Sun",
    sku: "BS-0015",
    description:
      "Cooling scalp shampoo for a refreshed feel. Cleanses gently while supporting a balanced scalp routine.",
    size: "300ml",
    weight: "300g",
    images: [
      "https://images.unsplash.com/photo-1620916566653-8fd8f4c86b2b?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [3, 2, 4],
  },
  {
    id: 16,
    name: "Hand Repair Cream",
    price: 7800,
    discountPercent: 8,
    inSale: true,
    stockCount: 26,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 3,
    category: "Sun",
    sku: "BS-0016",
    description:
      "Rich hand cream for dry hands. Smooth finish and comfortable daily moisture.",
    size: "75ml",
    weight: "75g",
    images: [
      "https://images.unsplash.com/photo-1629198726018-41b7b7a4b3b2?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [6],
  },
  {
    id: 17,
    name: "Body Scrub Polish",
    price: 15900,
    discountPercent: 14,
    inSale: true,
    stockCount: 8,
    outOfStock: false,
    image:
      "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 7,
    category: "Skin",
    sku: "BS-0017",
    description:
      "Exfoliating body scrub to help smooth the look of texture. Rinses clean with a soft feel.",
    size: "250g",
    weight: "250g",
    images: [
      "https://images.unsplash.com/photo-1620916566393-7c3a4a4f3f10?q=80&w=1200&auto=format&fit=crop",
    ],
  },
  {
    id: 18,
    name: "Aloe After-Sun Gel",
    price: 13200,
    discountPercent: 12,
    inSale: true,
    stockCount: 0,
    outOfStock: true,
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop",
    paymentProvider: "CocoPay",
    minInstallments: 3,

    brandId: 3,
    category: "Skin",
    sku: "BS-0018",
    description:
      "Cooling aloe gel for after-sun comfort. Lightweight feel with quick absorption.",
    size: "200ml",
    weight: "200g",
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop",
    ],
    concernIds: [1, 2, 5, 4],
  },
];

export const productFaq = [
  {
    id: "f1",
    productId: 1,
    q: "Is this suitable for sensitive skin?",
    a: "Yes, it’s designed to be gentle and hydrating. Patch test is recommended if you have very reactive skin.",
  },
  {
    id: "f2",
    productId: 1,
    q: "How often can I use it?",
    a: "Daily use is fine — morning and night depending on your routine.",
  },
  {
    id: "f3",
    productId: 4,
    q: "How long to see results?",
    a: "Many users notice improved glow in 2–4 weeks with consistent use.",
  },
  {
    id: "f4",
    productId: 10,
    q: "How often should I use the detox mask?",
    a: "1–2 times per week is ideal as a weekly reset step.",
  },
  {
    id: "f5",
    productId: 12,
    q: "Can I use this serum daily?",
    a: "Yes. Apply once or twice daily on clean skin before moisturizer.",
  },
  {
    id: "f6",
    productId: 14,
    q: "How often should I use the hair mask?",
    a: "1–2 times per week is ideal. Leave on for 5–10 minutes then rinse.",
  },
  {
    id: "f7",
    productId: 17,
    q: "Is the body scrub harsh?",
    a: "It’s designed to be gentle, but avoid using on broken or irritated skin.",
  },
  {
    id: "f8",
    productId: 18,
    q: "Can I use this aloe gel on face?",
    a: "It can be used lightly, but avoid eyes and do a patch test first.",
  },
];

export const productReviews = [
  {
    id: "r1",
    productId: 1,
    name: "Nadeesha",
    rating: 5,
    date: "2025-10-10",
    comment: "Super smooth and moisturizing. I noticed a difference in a week.",
    verified: true,
  },
  {
    id: "r2",
    productId: 1,
    name: "Amal",
    rating: 4,
    date: "2025-10-18",
    comment: "Good texture and non-greasy. Smells nice too.",
    verified: false,
  },
  {
    id: "r3",
    productId: 2,
    name: "Sahan",
    rating: 5,
    date: "2025-09-22",
    comment: "Very hydrating. Wish it was in stock more often!",
    verified: true,
  },
  {
    id: "r4",
    productId: 4,
    name: "Ishara",
    rating: 4,
    date: "2025-11-01",
    comment: "Brightening effect is real. Packaging looks premium.",
    verified: true,
  },
  {
    id: "r5",
    productId: 10,
    name: "Tharindu",
    rating: 4,
    date: "2025-11-20",
    comment: "Great weekly reset mask. Skin feels clean and refreshed.",
    verified: true,
  },
  {
    id: "r6",
    productId: 12,
    name: "Dinithi",
    rating: 5,
    date: "2025-12-02",
    comment: "Skin feels plump and hydrated. Works great under makeup.",
    verified: true,
  },
  {
    id: "r7",
    productId: 12,
    name: "Kasun",
    rating: 4,
    date: "2025-12-08",
    comment: "Nice serum, not sticky. Good for daily use.",
    verified: false,
  },
  {
    id: "r8",
    productId: 14,
    name: "Madhavi",
    rating: 5,
    date: "2025-11-28",
    comment: "Hair feels so soft after one use. Smells amazing too.",
    verified: true,
  },
  {
    id: "r9",
    productId: 15,
    name: "Hiruni",
    rating: 4,
    date: "2025-12-11",
    comment: "Refreshing on scalp. Cleans well without drying too much.",
    verified: true,
  },
  {
    id: "r10",
    productId: 16,
    name: "Nimal",
    rating: 5,
    date: "2025-12-18",
    comment: "Perfect for dry hands. Absorbs fast and feels premium.",
    verified: true,
  },
  {
    id: "r11",
    productId: 17,
    name: "Shehan",
    rating: 4,
    date: "2025-12-20",
    comment: "Good scrub, skin feels smooth after shower. Not too harsh.",
    verified: true,
  },
  {
    id: "r12",
    productId: 18,
    name: "Ruwani",
    rating: 4,
    date: "2025-12-23",
    comment: "Cooling and soothing. Wish it was in stock again!",
    verified: false,
  },
];

export const concerns = [
  { concernID: 1, concernType: "All Types", category: null },
  { concernID: 2, concernType: "Aging & Wrinkling", category: "Face" },
  { concernID: 3, concernType: "Acne Treatment", category: "Face" },
  { concernID: 4, concernType: "Sun Damage", category: "Skin" },
  { concernID: 5, concernType: "Dryness & Hydration", category: "Skin" },
  { concernID: 6, concernType: "Dark Spots & Brightening", category: "Face" },
  { concernID: 7, concernType: "Sensitive Skin", category: "Skin" },
];

export const BrandsList = [
  { id: 1, name: "The Ordinary", logo: "./images/Brandslogo/brand1.png" },
  { id: 2, name: "CeraVe", logo: "./images/Brandslogo/brand2.png" },
  { id: 3, name: "Aveeno", logo: "./images/Brandslogo/brand3.png" },
  { id: 4, name: "L'Oréal", logo: "./images/Brandslogo/brand4.png" },
  {
    id: 5,
    name: "Madagascar Centella",
    logo: "./images/Brandslogo/brand1.png",
  },
  { id: 6, name: "Vita C", logo: "./images/Brandslogo/brand2.png" },
  { id: 7, name: "Prévense", logo: "./images/Brandslogo/brand3.png" },
];
